### ISSUE TITLE
Running.ipynb doesn't run.

### ISSUE THREAD

**Issue by ncclementi** [bjmorgan/pyscses#12]
* Running notebook:
  Cell number 6:

```
NameError                                 Traceback (most recent call last)
<ipython-input-6-67db249c57f8> in <module>()
      4     for t in temp:
      5 
----> 6         defect_species = { l : DefectSpecies( l, v, m, mob ) for l, v, m, mob in zip( defect_labels, valence, m, mobilities ) }
      7 
      8         all_sites = Set_of_Sites.set_of_sites_from_input_data( data, [grid_x_min, grid_x_max], defect_species, site_charges, core_models, t )

NameError: name 'mobilities' is not defined
```

**Comment by georgiewellock** [comment]
I have updated the notebook to include the mobilities and now the notebook runs as it should. I have also added an expected run time to the top of this notebook: https://github.com/bjmorgan/pyscses/commit/b845a5d21a2748867977e5c23f38f7c6b9f168fd

**Comment by bjmorgan** [comment]
@georgiewellock Can you add the specs of the machine you ran on, e.g. iMac with ? processor?

**Comment by georgiewellock** [comment]
I have added the approximate timings and machine specifications to both the README and the userguide notebooks: https://github.com/bjmorgan/pyscses/commit/8ceeab33d066e1a50ab6180a362cac95fac6f1db

**Comment by ncclementi** [comment]
Great, thanks for adding this. I will be testing it today!
