### ISSUE TITLE
`userguides/notebooks/.ipynb_checkpoints`

### ISSUE THREAD

**Issue by ncclementi** [bjmorgan/pyscses#13]
Even though you have the `userguides/notebooks/.ipynb_checkpoints` in the `.gitignore` you still have some `ipynb_checkpoints` in the repository. You might want to do a `git rm` to remove them.

**Comment by georgiewellock** [comment]
Thanks, removed here: https://github.com/bjmorgan/pyscses/commit/07e17a4e8fb5d72d9f8bc6b189f714f9588b66bf

**Comment by bjmorgan** [comment]
Additional pruning of `**/.ipynb_checkpoints`: https://github.com/bjmorgan/pyscses/commit/bd0572e23e7e25389a00e8ceb0a1cb6c884d1f63
